# Generated by Django 4.2.2 on 2023-06-13 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filter_model',
            name='father',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='filter_model',
            name='mother',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='filter_model',
            name='occupation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
