# Generated by Django 4.2.2 on 2023-06-13 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_filter_model_father_filter_model_mother_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filter_model',
            name='DOB',
            field=models.DateField(blank=True, null=True),
        ),
    ]
